### ISSUE TITLE
Clearer README

### ISSUE THREAD

**Issue by ihshareef** [jmerdich/ros-skeltrack#1]
I've installed Skeltrack on my computer, and I'm trying to run this wrapper on my installation of ROS. I'm afraid that the README isn't very clear to me; it's perhaps because I'm quite new to ROS--is it possible to provide better instructions on running the wrapper? Thanks.

**Comment by ihshareef** [comment]
I figured it out, just run  `rosrun ros_skeltrack ros_skeltrack_node`

**Comment by jmerdich** [comment]
Yup, that's it, and that's considered a basic skill for working with ROS. Protip: if you're using Ubuntu, rosrun can tab-complete.

**Comment by ihshareef** [comment]
Thanks for the quick response. I'm a little new to ROS :)

On 31 August 2015 at 16:02, Jake Merdich notifications@github.com wrote:

> Yup, that's it, and that's considered a basic skill for working with ROS.
> Protip: if you're using Ubuntu, rosrun can tab-complete.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jmerdich/ros-skeltrack/issues/1#issuecomment-136379791
> .

## 

_Ibrahim Hussain Shareef_
